username:         rainbowbo
# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            编程人生
tagline:          '斯人若彩虹'
description:      'Hello,World! Here is my personal weblog about technology and life.'
#url:              http://shelldone.com

author:
  name:           'Rainbowbo'
  url:            https://github.com/rainbowbo
baseurl: /blog
paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
#comments :
 #   provider : duoshuo
 #   duoshuo :
   #   short_name : rainbow
